# Generated by Django 4.2.6 on 2023-10-31 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=14)),
                ('sexy', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10, null=True)),
                ('available_hours', models.CharField(blank=True, choices=[('oito', '8:00'), ('nove', '9:00'), ('dez', '10:00'), ('onze', '11:00'), ('doze', '12:00'), ('treze', '13:00'), ('quatorze', '14:00'), ('quinze', '15:00'), ('dezesseis', '16:00'), ('dezessete', '17:00'), ('dezoito', '18:00'), ('dezenove', '19:00'), ('vinte', '20:00')], max_length=10, null=True)),
                ('office', models.CharField(choices=[('barber', 'Barbeiro'), ('hairdresser', 'Cabeleireiro'), ('stylist_barber', 'Barbeiro Estilista'), ('receptionist', 'Recepcionista'), ('barbershop_manager', 'Gerente da Barbearia'), ('barber_assistant', 'Auxiliar de Barbeiro'), ('hair_treatment_specialist', 'Especialista em Tratamentos Capilares'), ('manicurist_pedicurist', 'Manicure/Pedicure'), ('facial_esthetician', 'Esteticista Facial'), ('masseuse_massagist', 'Massagista')], max_length=100)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(choices=[('haircut', 'Corte de Cabelo'), ('beard_trim', 'Barba e Bigode'), ('beard_design', 'Design de Barba'), ('full_beard', 'Barba Completa'), ('hair_treatments', 'Tratamentos Capilares'), ('hair_coloring', 'Coloração de Cabelo'), ('eyebrow_design', 'Design de Sobrancelha'), ('facial_massage', 'Massagens Faciais'), ('skin_care', 'Tratamentos de Pele'), ('hair_cauterization', 'Cauterização de Fios'), ('beard_hydration', 'Hidratação de Barba'), ('sideburn_trim', 'Aparar Costeletas'), ('beard_cauterization', 'Cauterização da Barba'), ('acne_facial_treatment', 'Tratamento de Acne Facial'), ('dark_circle_treatment', 'Tratamento de Olheiras')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.collaborator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
    ]
