# Generated by Django 4.2.6 on 2023-10-31 21:55

import datetime
from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='day',
            field=models.DateField(default=datetime.date.today, help_text='Insira uma data para agenda', validators=[schedule.models.validate_day]),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='hours',
            field=models.CharField(choices=[('1', '8:00'), ('2', '9:00'), ('3', '10:00'), ('4', '11:00'), ('5', '12:00'), ('6', '13:00'), ('7', '14:00'), ('8', '15:00'), ('9', '16:00'), ('10', '17:00'), ('11', '18:00'), ('12', '19:00'), ('13', '20:00')], default=0.0, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='scheduling',
            unique_together={('hours', 'day')},
        ),
    ]
