# Generated by Django 4.2.6 on 2023-11-01 06:53

import datetime
from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduling_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='day',
            field=models.DateField(default=datetime.date.today, validators=[schedule.models.validate_day]),
        ),
    ]
