# Generated by Django 4.2.6 on 2023-11-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_scheduling_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduling',
            unique_together=set(),
        ),
    ]
