# Generated by Django 4.2.6 on 2023-11-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_scheduling_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='service',
            field=models.CharField(choices=[('haircut', 'Corte de Cabelo'), ('beard_trim', 'Barba e Bigode'), ('beard_design', 'Design de Barba'), ('full_beard', 'Barba Completa'), ('hair_treatments', 'Tratamentos Capilares'), ('hair_coloring', 'Coloração de Cabelo'), ('eyebrow_design', 'Design de Sobrancelha'), ('facial_massage', 'Massagens Faciais'), ('skin_care', 'Tratamentos de Pele'), ('hair_cauterization', 'Cauterização de Fios'), ('beard_hydration', 'Hidratação de Barba'), ('sideburn_trim', 'Aparar Costeletas'), ('beard_cauterization', 'Cauterização da Barba'), ('acne_facial_treatment', 'Tratamento de Acne Facial'), ('dark_circle_treatment', 'Tratamento de Olheiras')], default=1, max_length=45),
        ),
    ]
